# Luiz Gatão Config

bindsym $mod+t exec --no-startup-id ~/dotfiles/scripts/toggle-theme.sh

bindsym $mod+p move workspace to output left
bindsym $mod+Shift+p exec flameshot gui

# Atalho para DESATIVAR (Modo Café/Apresentação)
# Desativa tanto o screensaver quanto o gerenciamento de energia (DPMS)
bindsym $mod+Shift+d exec --no-startup-id xset s off -dpms && notify-send "Inatividade" "Bloqueio automático DESATIVADO"

# Atalho para ATIVAR (Volta ao padrão de 5 minutos)
bindsym $mod+Shift+a exec --no-startup-id xset s 300 300 && xset +dpms && notify-send "Inatividade" "Bloqueio automático ATIVADO (5 min)"
