#!/usr/env/bin bash
# vim: set filetype=sh :
# shellcheck disable=SC1091,SC2154

export KEYTIMEOUT=30
export EDITOR="nvim"
export VISUAL="nvim"
export TABSIZE=2
export SSH_TERM="xterm-256color"
export PROJECTS_DIR="${HOME}/Documentos/Dev"

ZSH_HIGHLIGHT_STYLES[comment]='fg=240'
ZSH_HIGHLIGHT_STYLES[default]='fg=251'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'

export OLLAMA_HOST=127.0.0.1:11434
export OLLAMA_TIMEOUT_MS=10000
export OLLAMA_LOAD_TIMEOUT='10m'
export OLLAMA_KEEP_ALIVE='10m'

export FZF_DEFAULT_OPTS='
  --color=fg:#c0c0da,fg+:#f0efff,bg:#0a0a14,bg+:#242436
  --color=hl:#37feb7,hl+:#72ffcd,info:#30f4f2,marker:#30f4f2
  --color=prompt:#c0c0da,spinner:#30f4f2,pointer:#30f4f2,header:#30f4f2
  --color=gutter:#0a0a14,border:#0a0a14,separator:#6a6a8a,scrollbar:#6a6a8a
  --color=label:#c0c0da,query:#c0c0da
  --preview-window="border-rounded" --prompt="> " --marker=">" --pointer="◆"
  --separator="─" --scrollbar="│" --layout="reverse"'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# BE SURE TO FIX THE ENV VARIABLES
# brew install libpq --build-from-source
# brew install mysql-client
# brew install openssl
# brew install curl

if [ "$(uname -s)" = "Linux" ]; then
  PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

export PYENV_ROOT="${HOME}/.pyenv"
PATH="${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${PATH}"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

. "$HOME/.local/bin/env"
[ -f ~/.fzf.zsh ] && . "${HOME}/.fzf.zsh"

if [[ "$(uname -s)" == "Linux" ]]; then
  [[ -r "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh" ]] &&
    . "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh"
fi

if [[ "$(command -v docker)" && -f "${HOME}/.docker/completions/_docker" ]]; then
  eval "$(docker completion zsh)"
fi

if [[ "$(command -v gh)" ]]; then
  eval "$(gh completion -s zsh)"
fi

# bun
export BUN_INSTALL="$HOME/.bun"
PATH="$BUN_INSTALL/bin:$PATH"

# Added by Antigravity
PATH="$HOME/.antigravity/antigravity/bin:$PATH"

PATH="$PATH:/opt/nvim/"

export PATH
