# THEME — dark (cyan/black)
set -g status-left-style NONE
set -g status-right-style NONE

# Status right
set -g status-right-length 100
set -g status-right "#{?client_prefix,#[fg=black bg=cyan]#[fg=cyan bold \
bg=black] #S #D ,#[fg=black bg=cyan]#[fg=white dim bg=black] #S #D }"

# Messages
set -g message-style "fg=cyan,bg=black"
set -g message-command-style "fg=cyan,bg=black"

# Enable status bar
set -g status "on"
set -g status-justify "left"

# Normal window colors. They have the same bg as the status bar
setw -g window-status-style "NONE,fg=black,bg=cyan"
# Arrow pointing forward in normal windows. Here we have one arrow
# before and other after the text as in:  id:name flags
# Both arrows have the save bg and fg as the status bar.
setw -g window-status-format "#[fg=cyan,bg=cyan]#[default] #I:#W #F \
#[fg=cyan,bg=cyan]#[default]"
# The current window also have both arrows, except its bg is black
# and fg cyan.
setw -g window-status-current-format "#[fg=cyan,bg=black]#[fg=white,\
bg=black] #I:#W #F #[fg=black,bg=cyan]#[default]"

# Reset some style if it is configured
setw -g window-status-separator ""
setw -g window-status-activity-style ""

set -g mode-style "fg=cyan,bg=black"
set -g message-command-style "fg=cyan,bg=black"
set -g message-style "fg=cyan,bg=black"

# This is the status default color. These colors have to match the colors
# configured in lines above.
set -g status-style "fg=black,bg=cyan"

# Status left
set -g status-left-length 100
set -g status-left '#[fg=cyan,bg=black]#(ps ax -o comm= -p "#{client_pid}" 2>/dev/null | \
grep -q sshd && printf " [SSH]")\
#{?client_prefix, [#h] ✼ ,#[fg=white dim bg=black] [#h] - \
#[default]}#[fg=black,bg=cyan]#[default]'
