# THEME — light (Tokyo Night Day)
set -g status-left-style NONE
set -g status-right-style NONE

# Status right
set -g status-right-length 100
set -g status-right "#{?client_prefix,#[fg=#e1e2e7 bg=#2e7de9]#[fg=#2e7de9 bold \
bg=#e1e2e7] #S #D ,#[fg=#e1e2e7 bg=#2e7de9]#[fg=#3760bf dim bg=#e1e2e7] #S #D }"

# Messages
set -g message-style "fg=#2e7de9,bg=#e1e2e7"
set -g message-command-style "fg=#2e7de9,bg=#e1e2e7"

# Enable status bar
set -g status "on"
set -g status-justify "left"

# Normal window colors
setw -g window-status-style "NONE,fg=#3760bf,bg=#e1e2e7"
setw -g window-status-format "#[fg=#e1e2e7,bg=#e1e2e7]#[default] #I:#W #F \
#[fg=#e1e2e7,bg=#e1e2e7]#[default]"
# Current window: blue accent background
setw -g window-status-current-format "#[fg=#e1e2e7,bg=#2e7de9]#[fg=#e1e2e7,\
bg=#2e7de9] #I:#W #F #[fg=#2e7de9,bg=#e1e2e7]#[default]"

# Reset some style
setw -g window-status-separator ""
setw -g window-status-activity-style ""

set -g mode-style "fg=#e1e2e7,bg=#2e7de9"
set -g message-command-style "fg=#2e7de9,bg=#e1e2e7"
set -g message-style "fg=#2e7de9,bg=#e1e2e7"

set -g status-style "fg=#3760bf,bg=#e1e2e7"

# Status left
set -g status-left-length 100
set -g status-left '#[fg=#e1e2e7,bg=#2e7de9]#(ps ax -o comm= -p "#{client_pid}" 2>/dev/null | \
grep -q sshd && printf " [SSH]")\
#{?client_prefix, [#h] ✼ ,#[fg=#3760bf dim bg=#e1e2e7] [#h] - \
#[default]}#[fg=#2e7de9,bg=#e1e2e7]#[default]'
